DROP TABLE IF EXISTS wildlife.LIVES_IN;
DROP TABLE IF EXISTS wildlife.SURVEY_ANIMAL;
DROP TABLE IF EXISTS wildlife.PHONE_NUMBERS;
DROP TABLE IF EXISTS wildlife.POP_SURVEY;
DROP TABLE IF EXISTS wildlife.POPULATION;
DROP TABLE IF EXISTS wildlife.ANIMAL;
DROP TABLE IF EXISTS wildlife.SPECIES;
DROP TABLE IF EXISTS wildlife.HABITAT;
DROP TABLE IF EXISTS wildlife.LOCATION;
DROP TABLE IF EXISTS wildlife.ORGANIZATION;



CREATE TABLE wildlife.ORGANIZATION (

O_ID INT NOT NULL,

Org_Name VARCHAR(64) NOT NULL UNIQUE CHECK (Org_Name <> ''),

Size INT NOT NULL CHECK (Size > 0),

Web_Domain VARCHAR(64) NOT NULL UNIQUE CHECK (Web_Domain LIKE '%.%'),

PRIMARY KEY (O_ID)

);

CREATE TABLE wildlife.PHONE_NUMBERS (

	Phone_Number BIGINT CHECK (
	Phone_Number IS NULL OR
	(Phone_Number BETWEEN 1000000000 AND 9999999999)
	),

O_ID INT NOT NULL,

PRIMARY KEY(Phone_Number),

FOREIGN KEY (O_ID) REFERENCES wildlife.ORGANIZATION(O_ID)
);

CREATE TABLE wildlife.LOCATION (

CODE INT(8) NOT NULL,

Region VARCHAR(64) NOT NULL,

Full_Name VARCHAR(64) NOT NULL,

PRIMARY KEY (CODE)

);

CREATE TABLE wildlife.POPULATION (

P_ID INT(8) NOT NULL,

Migration_Pattern VARCHAR(256) CHECK (LENGTH(Migration_Pattern) > 0),,

Pop_Name VARCHAR(64) NOT NULL CHECK (Pop_Name <> ''), 

L_CODE INT(8) NOT NULL,

PRIMARY KEY (P_ID),

FOREIGN KEY (L_CODE) REFERENCES wildlife.LOCATION(CODE) ON DELETE CASCADE
);

/*INSERT INTO wildlife.Organization
VALUES (10000001,'Animal Planet', 20000, '3105551234', 'www.animalplanet.com'),
	  (10000002,'San Diego Zoo',1000, '3105554321','Sandiegozoo.com');*/




CREATE TABLE wildlife.POP_SURVEY (

P_ID INT(8) NOT NULL,

Date Datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,

Size INT NOT NULL CHECK (Size > 0) DEFAULT 1,

O_ID INT NOT NULL,

PRIMARY KEY (P_ID, Date),

FOREIGN KEY (O_ID) REFERENCES wildlife.ORGANIZATION(O_ID) ON DELETE CASCADE,

FOREIGN KEY (P_ID) REFERENCES wildlife.POPULATION(P_ID) ON DELETE CASCADE

);

/*SELECT * FROM wildlife.POP_SURVEY;*/

CREATE TABLE wildlife.SPECIES (

S_ID INT(8) NOT NULL,

Scientific_Name VARCHAR(32) NOT NULL UNIQUE CHECK (Scientific_Name <> ''),

Common_Name VARCHAR(64) NOT NULL UNIQUE CHECK (Common_Name <> ''),

PRIMARY KEY (S_ID)

);




CREATE TABLE wildlife.ANIMAL (

TRACKING_ID INT(8) NOT NULL,

Age INT NOT NULL CHECK (Age >= 0),

NAME VARCHAR(32),

Date_Tagged Datetime DEFAULT CURRENT_TIMESTAMP,

Sex VARCHAR(6) NOT NULL CHECK (Sex IN ('Male', 'Female', 'Unknown')), 

PRIMARY KEY (TRACKING_ID)

);


CREATE TABLE wildlife.HABITAT (

H_ID INT(8) NOT NULL,

Name VARCHAR(64) NOT NULL CHECK (Name <> ''),

Climate VARCHAR(64) NOT NULL CHECK (Climate <> ''), 

PRIMARY KEY (H_ID)

);

CREATE TABLE wildlife.SURVEY_ANIMAL (
P_ID INT(8) NOT NULL,

S_ID INT(8) NOT NULL,

TRACKING_ID INT(8) NOT NULL,

FOREIGN KEY (P_ID) REFERENCES wildlife.POP_SURVEY(P_ID) ON DELETE CASCADE,

FOREIGN KEY (S_ID) REFERENCES wildlife.SPECIES(S_ID) ON DELETE CASCADE,

FOREIGN KEY (TRACKING_ID) REFERENCES wildlife.ANIMAL(TRACKING_ID) ON DELETE CASCADE
);

CREATE TABLE wildlife.LIVES_IN (
H_ID INT(8) NOT NULL,

S_ID INT(8) NOT NULL,

FOREIGN KEY (H_ID) REFERENCES wildlife.HABITAT(H_ID) ON DELETE CASCADE,

FOREIGN KEY (S_ID) REFERENCES wildlife.SPECIES(S_ID) ON DELETE CASCADE
);
/*SELECT * FROM wildlife.POP_SURVEY;*/
